### ISSUE TITLE
Exception on Compiled Version

### ISSUE THREAD

**Issue by pogzie** [mjungnickel18/papyruscs#11]
I gave up on the binary, I dont know if the latest release already included the latest updates (using `PapyrusCs --version` just show version 1.0.0. I doubt thats the real version. 

Now on a compiled version, im getting this exception: 

```
402 44 43 43

402 44 43 43
2175 of 14761 Chunks render @ 5.4 cps
402 44 44 44
DbUpdate complete

1817, 9178

402 44 44 44

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at PapyrusCs.Program.RunMapCommand(Options options) in /root/papyruscs/PapyrusCs/Program.cs:line 558
   at PapyrusCs.Program.<>c.<Main>b__4_0(Options opts) in /root/papyruscs/PapyrusCs/Program.cs:line 52
   at PapyrusCs.Program.Main(String[] args) in /root/papyruscs/PapyrusCs/Program.cs:line 49
```

**Comment by mjungnickel18** [comment]
Does it happen with the latest version? 0.4.0?

**Comment by pogzie** [comment]
i have not yet tried papyruscs after abandoning it for papyrusjs as the cs version running on a dockerized container requires too much resources I am willing to allot.
