### ISSUE TITLE
System.AccessViolationException

### ISSUE THREAD

**Issue by MarkHalpap** [mjungnickel18/papyruscs#26]
V0.4.0 Win64

Ran it on a small test world: all fine.

Ran it on a somewhat bigger world and got an error after a while:

.\PapyrusCs.exe --world "../minecraftWorlds/My World/db" --output "C:\tmp\myworld"

171885 of 536568 Chunks render @ 172,1 cps     Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at leveldb_sharp_std.Native.leveldb_get(IntPtr, IntPtr, IntPtr, UIntPtr, UIntPtr ByRef, IntPtr ByRef)
   at leveldb_sharp_std.Native.leveldb_get(IntPtr, IntPtr, IntPtr, UIntPtr, UIntPtr ByRef, IntPtr ByRef)
   at leveldb_sharp_std.Native.leveldb_get(IntPtr, IntPtr, Byte[])
   at Maploader.World.World.GetChunkData(Maploader.World.GroupedChunkSubKeys)
   at PapyrusCs.Strategies.Dataflow.GetDataBlock+<>c__DisplayClass4_0.<.ctor>b__0(System.Collections.Generic.IEnumerable`1<Maploader.World.GroupedChunkSubKeys>)
   at System.Threading.Tasks.Dataflow.TransformManyBlock`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=***],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=***]].ProcessMessage(System.Func`2<System.__Canon,System.Collections.Generic.IEnumerable`1<System.__Canon>>, System.Collections.Generic.KeyValuePair`2<System.__Canon,Int64>)
   at System.Threading.Tasks.Dataflow.TransformManyBlock`2+<>c__DisplayClass9_0[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=***],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=***]].<.ctor>b__3(System.Collections.Generic.KeyValuePair`2<System.__Canon,Int64>)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=***]].ProcessMessagesLoopCore()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by karpana** [comment]
Is there a chance you could provide the following
1) the specific version/build of Windows 10 64-bit?
2) the amount of RAM this machine has?
3) the total size (in megabytes) of the world?
4) the results of running this same test using the latest version of PapyrusCs (0.5.0)?

**Comment by HereToHelp777** [comment]
I had the same issue. 

I just kept running the program over and over and finally it completed and made my map.html 

I have no clue why it worked or how any people of this worked. But I just thought I'd pop in and mention what worked for me. Good luck!

**Comment by dkelley044** [comment]
I am also having this issue... on a very large world.
I am having this same issue on another machine as well (I've copied the world to a laptop to try and run it there, same issue/crash message)

I have installed .net info at the end past the error message, I have tried with binary papyrusCS download, as well as compiled-on-this-machine papyrus.


Windows version on both is Microsoft Windows [Version 10.0.19042.685]
Desktop: i7-3770 on MSI Z77A-GD65 Gaming Motherboard (Intel Ivy Bridge Chipset, Z77 Southbridge. 16GB Ram (DDR3, Dual Channel, Corsair )
Laptop: i7-10510U on Dell 0NNGJG Mainboard (Intel Comet Lake Chipset, Intel Comet Lake PCH Southbridge) 16GB Ram (DDR4, Dual Channel, SK Hynix)
World Size (DB Folder) 34,283,967,843 Bytes (31.9GB)


After the first run, CPS rate drops from ~50-70 Chunks Per Second to 5-10cps.


Output:

Opening world...
Generating a list of all chunk keys in the database.
This could take a few minutes (This takes a long time. I haven't measured, but say... 20 minutes or so?
Total Chunk count 10619855

The total dimensions of the map are
  X: -2304 to 2327
  Z: -1323 to 1151

Tilesize is 512x512
Reading terrain_texture.json...

The maximum diameter of the map is 4632
For 2 chunks per tile, new max diameter is 2316
To generate the zoom levels, we expand the diameter to 4096
This results in 13 zoom levels
Overriding settings with: Format png, Quality -1 ChunksPerDimension 2
Setting Zoom levels to 20 down to 8
Found 6339373 subchunks which are already rendered
Grouping subchunks... 10619855
Grouped by 2 to 2655127 tiles
Average of 4.0 chunks per tile
Queue Stat: GetData 3 Render 0 Save 0 Db 0
Queue Stat: GetData 0 Render 0 Save 0 Db 0
_**... this repeats for a while until it gets to the next chunks that need to be rendered ---**_
33688 of 10619855 Chunks render @ 10.6 cps     Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at leveldb_sharp_std.Native.leveldb_get(IntPtr, IntPtr, IntPtr, UIntPtr, UIntPtr ByRef, IntPtr ByRef)
   at leveldb_sharp_std.Native.leveldb_get(IntPtr, IntPtr, IntPtr, UIntPtr, UIntPtr ByRef, IntPtr ByRef)
   at leveldb_sharp_std.Native.leveldb_get(IntPtr, IntPtr, Byte[], UIntPtr ByRef)
   at Maploader.World.World.GetChunkData(Maploader.World.GroupedChunkSubKeys)
   at PapyrusAlgorithms.Strategies.Dataflow.GetDataBlock+<>c__DisplayClass3_0.<.ctor>b__0(System.Collections.Generic.IEnumerable`1<Maploader.World.GroupedChunkSubKeys>)
   at System.Threading.Tasks.Dataflow.TransformManyBlock`2[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessMessage(System.Func`2<System.__Canon,System.Collections.Generic.IEnumerable`1<System.__Canon>>, System.Collections.Generic.KeyValuePair`2<System.__Canon,Int64>)
   at System.Threading.Tasks.Dataflow.TransformManyBlock`2+<>c__DisplayClass9_0[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].<.ctor>b__3(System.Collections.Generic.KeyValuePair`2<System.__Canon,Int64>)
   at System.Threading.Tasks.Dataflow.Internal.TargetCore`1[[System.__Canon, System.Private.CoreLib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ProcessMessagesLoopCore()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(System.Threading.Thread, System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef, System.Threading.Thread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()


C:\Program Files\dotnet>dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  3.0.103 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by HereToHelp777** [comment]
I ended up resolving my issues with it by just running it over and over and
over again. Each time it saves a little more.

It's a total pain in the ass to watch the computer all day to rerun as
necessary but eventually it works.

Also, I should note that I sent the world file to a friend with a much
better conputer who plays on my realm and he didn't experience any of the
stoppage issues. So I think it's our comouters fault over anyrhing else.
