### ISSUE TITLE
SQLite Error 14

### ISSUE THREAD

**Issue by OptimalGrammar** [mjungnickel18/papyruscs#45]
I just tryed to use this on my Minecraft World from the Bedrock server I'm running, & this is the error I got in command prompt. Could somebody point me in the right direction for fixing this?

```
Opening world...
Generating a list of all chunk keys in the database.
This could take a few minutes
Total Chunk count 32832

The total dimensions of the map are
  X: -181 to 220
  Z: -136 to 142

Tilesize is 512x512
Reading terrain_texture.json...

The maximum diameter of the map is 402
For 2 chunks per tile, new max diameter is 201
To generate the zoom levels, we expand the diameter to 256
This results in 9 zoom levels
Unhandled exception. Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.Migrate(String targetMigration)
   at Microsoft.EntityFrameworkCore.RelationalDatabaseFacadeExtensions.Migrate(DatabaseFacade databaseFacade)
   at PapyrusCs.Strategies.Dataflow.DataFlowStrategy`1.Init() in C:\projects\papyruscs-19426\PapyrusCs\Strategies\Dataflow\DataFlowStrategy.cs:line 416
   at PapyrusCs.Program.RunMapCommand(Options options) in C:\projects\papyruscs-19426\PapyrusCs\Program.cs:line 428
   at PapyrusCs.Program.<>c.<Main>b__4_0(Options opts) in C:\projects\papyruscs-19426\PapyrusCs\Program.cs:line 49
   at CommandLine.ParserResultExtensions.MapResult[T1,T2,T3,TResult](ParserResult`1 result, Func`2 parsedFunc1, Func`2 parsedFunc2, Func`2 parsedFunc3, Func`2 notParsedFunc)
   at PapyrusCs.Program.Main(String[] args) in C:\projects\papyruscs-19426\PapyrusCs\Program.cs:line 46
```

**Comment by OptimalGrammar** [comment]
I'm an idiot, needed to run as admin!
